const SET_PLAYER_DATA_ACTION = "SET_PLAYER_DATA_ACTION";
const RESET_PLAYER_ACTION = "RESET_PLAYER_ACTION";
const SET_BATTLE_BTN_ACTION = "SET_BATTLE_BTN_ACTION";
const SET_PLAYERS_REPOS_ACTION = "SET_PLAYERS_REPOS_ACTION";
const SET_PLAYER_SCORE_ACTION = "SET_PLAYER_SCORE_ACTION";
const SET_RESTART_BTN_ACTION = "SET_RESTART_BTN_ACTION";
const RESET_PLAYERS_ACTION = "RESET_PLAYERS_ACTION";
const RESET_SCORE_ACTION = 'RESET_SCORE_ACTION'

export {
  SET_PLAYER_DATA_ACTION,
  RESET_PLAYER_ACTION,
  SET_BATTLE_BTN_ACTION,
  SET_PLAYERS_REPOS_ACTION,
  SET_PLAYER_SCORE_ACTION,
  SET_RESTART_BTN_ACTION,
  RESET_PLAYERS_ACTION,
  RESET_SCORE_ACTION
};
